language: python
install:
  - pip install bashate
  - pip install rstcheck
script:
  - rstcheck README.rst
  - bashate common_functions
  - bashate install_docker.sh
  - bashate install_jekyll.sh
  - bashate install_znc.sh
  - bashate change_kernel.sh
