language: python
install:
  - pip install bashate
  - pip install rstcheck
script:
  - rstcheck README.rst
  - bashate -e E006 common_functions
  - bashate -e E006 install_docker.sh
  - bashate -e E006 install_jekyll.sh
  - bashate -e E006 install_znc.sh
  - bashate -e E006 change_kernel.sh
