#!/bin/bash

# ============================================================================
# This file is meant to hold all common package installation used across the
# install scripts under this project.
# Specifically those that require a special configuration or need several
# libraries to be installed to work properly
# e.x. mysql
# ============================================================================

# Uncomment the following line to debug this script
# set -o xtrace

source common_functions

SetPackageManager

#=================================================
#=================================================

function CreateSelfSignedCertificate {
    # To use an SSL certificate to secure a service but without
    # requiring a CA-signed certificate - i.e sign your own certificates.
    # users will be displayed a browser warning about certificate not trusted.
    # See http://do.co/2gtYDet

    cert_path="${1}"
    subj=${2:-/C=US/ST=Oregon/L=Portland/O=Dlux/OU=Data Center/CN=Dlux}

    [[ ! -d $cert_path ]] && PrintError "Directory ${cert_path} does not exists."
    pushd $cert_path

    openssl req -newkey rsa:4096 -nodes -keyout domain.key \
       -x509 -days 365 -out domain.crt -subj "${subj}"

    popd
}

function CreateSelfCASignedCertificate {

    cert_path="${1}"
    subj=${2:-/C=US/ST=Oregon/L=Portland/O=Dlux/OU=Data Center/CN=Dlux}
    [[ ! -d $cert_path ]] && PrintError "Directory ${cert_path} does not exists."
    pushd $cert_path

    # 1. Generate 4096-bit long RSA key for root CA.
    openssl genrsa -out ca.key 4096
    # 2. Create self-signed 5y valid root CA certificate.
    openssl req -new -x509 -days 1826 \
        -key ca.key -out ca.crt -subj "${subj}"
    # 3. Create subordinate CA to be used for the signing. This means:
    # create key, create csr, & process csr to get a crt signed by the root CA.
    # KEY
    openssl genrsa -out ia.key 4096
    # CSR
    openssl req -new -key ia.key -out ia.csr -subj "${subj}"
    # 5. CRT (Signed)
    openssl x509 -req -days 730 -set_serial 01 \
        -CA ca.crt -CAkey ca.key -in ia.csr -out ia.crt
    popd
}

function CreateCSRCertificate {
    cert_path="${1}"
    [[ ! -d $cert_path ]] && PrintError "Directory ${cert_path} does not exists."
    pushd $cert_path

    # Use this method to secure an Apache HTTP or Nginx web server (SSL-HTTPS).
    # Use when using a Certificate Authority (CA) to issue the SSL certificate.
    # Created pPrivate key and csr must be send to a CA to request a CA-signed SSL cert.
    openssl req \
       -newkey rsa:2048 -nodes -keyout domain.key \
       -out domain.csr
    popd
}

function CustomizeApache {
    Customize"${_PACKAGE_MANAGER}"Apache
}

function InstallApache {
    Install"${_PACKAGE_MANAGER}"Apache
}

function InstallApacheMod {
    Install"${_PACKAGE_MANAGER}"ApacheMod "$@"
}

function InstallJenkins {
    Install"${_PACKAGE_MANAGER}"Jenkins "$@"
}

function InstallMysql {
    # Can accept a password
    Install"${_PACKAGE_MANAGER}"Mysql "$@"
}

function InstallNginx {
    Install"${_PACKAGE_MANAGER}"Nginx
}

function InstallNodejs {
    # Can accept a integer representing a major version [4 to 8].
    # Defaults to version 8
    Install"${_PACKAGE_MANAGER}"Nodejs "$@"
}

function InstallPhp {
    # Can accept php version to install 5.5 or 7.0
    Install"${_PACKAGE_MANAGER}"Php "$@"
}

function InstallTftp {
    # Can accept string "upload" to enable upload feature
    Install"${_PACKAGE_MANAGER}"Tftp "$@"
}

function UninstallApache {
    Uninstall"${_PACKAGE_MANAGER}"Apache
}

function UninstallMysql {
    Uninstall"${_PACKAGE_MANAGER}"Mysql
}

function WaitForJenkinsSvr {
    attemptCount=1
    maxAttempts=${1:-100}

    echo "Waiting jenkins status to be active..."
    while [ "$attemptCount" -le "$maxAttempts" ]; do
        echo "Attempt:  $attemptCount of $maxAttempts"
        tmp=$(systemctl status jenkins | grep -s 'Active: active')
        [[ -z $tmp ]] && attemptCount=$(($attemptCount + 1)) && sleep 1s || break
    done

    [[ -z $(systemctl status jenkins | grep -s 'Active: active') ]] && PrintError "Timeout after $maxAttempts sec." || echo 'Jenkins Launched'
}

#=================================================
# APT PACKAGE FUNCTIONS
#=================================================

function CustomizeaptApache {

    # Verify apache is installed
    msg="Apache server is not installed"
    [[ -z $( ps aux | grep apache2 | grep -v grep ) ]] && PrintError "${msg}"

    mkdir -p /var/www/html/customErrors

    cat <<EOF > "/var/www/html/customErrors/c403.html"
<h1 style='color:red'>Permission Denied</h1>
<p>You have no permission to access this page :-(</p>
<p>If you think you should be able to see this page contact your admin.</p>
EOF

    cat <<EOF > "/var/www/html/customErrors/c404.html"
<h1 style='color:red'>Error 404: Not found :-(</h1>
<p>No idea where that file is, sorry. Is it the correct URL?</p>
EOF

    cat <<EOF > "/var/www/html/customErrors/c50x.html"
<h1>Oops! Something went wrong...</h1>
<p>We seem to be having some technical difficulties. Hang tight.</p>
EOF

    sed -i 's/<\/VirtualHost>//g' /etc/apache2/sites-enabled/000-default.conf
    cat <<EOF >> "/etc/apache2/sites-enabled/000-default.conf"
        ErrorDocument 403 /customErrors/c403.html
        ErrorDocument 404 /customErrors/c404.html
        ErrorDocument 500 /customErrors/c50x.html
</VirtualHost>
EOF

    service apache2 restart
}

function InstallaptApache {
    # Verify Apache is not already installed
    if [[ -z $( ps aux | grep apache2 | grep -v grep ) ]]; then
        apt-get install -y apache2 apache2-utils
        # Disable directory browsing
        sed -i 's/Options Indexes/Options/g' /etc/apache2/apache2.conf

        service apache2 restart 
    fi
}

function InstallaptApacheMod {
    # Verify Apache is installed
    mod="${1}"
    [[ -z $( ps aux | grep apache2 | grep -v grep ) ]] && PrintError "Apache must be installed and running"
    [[ -z "${mod}" ]] && PrintError "Expecting a mod name to install e.g. wsgi"

    if [[ $mod == 'proxy' ]]; then
        echo "mod-proxy Under Development. Need to be verified."
        #apt-get install -y build-essential libapache2-mod-proxy-html libxml2-dev
        # Enable modules
        a2enmod proxy
        a2enmod proxy_http headers
        #a2enmod proxy_html proxy_balancer
        #a2enmod proxy_ajp rewrite deflate headers proxy_balancer
        #a2enmod proxy_connect
    #
    elif [[ $mod == 'wsgi' ]]; then
        apt-get install -y libexpat1 ssl-cert
        apt-get install -y libapache2-mod-wsgi
        echo "mod-wsgi installed"
    else
        PrintError " mod-$mod NOT found."
    fi
    service apache2 restart
}

function InstallaptJenkins {
  apt-get -y -qq update

  # if jenkins not installed then install it
  # if instaled it will be updated
  if [ ! -f /etc/init.d/jenkins ]; then
    wget -qO- https://pkg.jenkins.io/debian/jenkins-ci.org.key | apt-key add -
    echo 'deb http://pkg.jenkins.io/debian-stable binary/' > /etc/apt/sources.list.d/jenkins.list
    apt-get -y -qq update
  fi

  apt-get install -y jenkins

  # Use given port for Jenkins
  [[ -n "$1" ]] && sed -i "s/^HTTP_PORT=..../HTTP_PORT=${1}/g" /etc/default/jenkins
  WaitForJenkinsSvr 10
}

function InstallaptMysql {
    # MySQL - Needs a password for DB_root user
    [[ -z $1 ]] && PrintError "Mysql need a password for DB root user"
    # Make sure not installed
    if [[ -n $(dpkg --get-selections | grep mysql) ]]; then
        echo "Mysql is already installed!!"
        return
    fi
    echo "Installing MySQL server"
    apt-get install -y python-setuptools python-mysqldb
    debconf-set-selections <<< "mysql-server mysql-server/root_password password ${1}"
    debconf-set-selections <<< "mysql-server mysql-server/root_password_again password ${1}"
    apt-get install -y mysql-server
}

function HardeningaptMysql {
# Hardening mysql script output keep changing:
#mysql_secure_installation
#unable to run it unatended just with expect which is tight to string output

mysql -uroot -p"${1}" <<MYSQL_SCRIPT
/* Remove anonymous users */
DELETE FROM mysql.user WHERE User='';
/* Remove remote root */
DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
/* Remove test database */
DROP DATABASE test;
/* Removing privileges on test database */
DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
/* Install validate_password plugin */
INSTALL PLUGIN validate_password SONAME 'validate_password.so';

FLUSH PRIVILEGES;
MYSQL_SCRIPT

}

function InstallaptNginx {
    apt-get install -y nginx
}

function InstallaptNodejs {
    version=${1:-8}
    curl -sL https://deb.nodesource.com/setup_"${version}".x | bash -
    apt-get install -y nodejs
}

function InstallaptPhp {
    release="${1:-$(lsb_release -rs)}"
    if [[ $release == 14.* || $release == 5.* ]]; then
        echo "Installing PHP 5.5"
        apt-geit install -y php5 libapache2-mod-php5 php5-mcrypt php5-cli \
        php5-curl php5-mysql php5-ldap php5-gd php5-json
        php5enmod mcrypt
    #elif [[ $release == 16.* || $release == 7.* ]]; then
    else
        echo "Installing PHP 7.0"
        apt-get -y install php7.0 libapache2-mod-php7.0 php7.0-mcrypt \
        php-memcache php7.0-mysql php7.0-curl php7.0-gd php7.0-xmlrpc \
        php7.0-xsl php7.0-mbstring php-gettext
    fi

    # mover index.php como primer opcion para apache
    cat <<EOF >> "/etc/apache2/mods-enabled/dir.conf"
<IfModule mod_dir.c>
          DirectoryIndex index.php index.html index.cgi index.pl index.php index.xhtml index.htm
</IfModule>
EOF
    cat <<EOF > "/var/www/html/info.php"
<?php
phpinfo();
?>
EOF

    service apache2 restart

}

function InstallaptTftp {
    echo "Installing TFTP-HPA server."
    apt-get install -y tftpd-hpa tftp
    if [[ $1 -eq 'upload' ]]; then
        echo "Allowing upload into the server."
        cp /etc/default/tftpd-hpa /etc/default/tftpd-hpa.ORIGINAL
        sed -i '/TFTP_OPTIONS/c\' /etc/default/tftpd-hpa
        echo 'TFTP_OPTIONS="--secure --create"' >>  /etc/default/tftpd-hpa
        chown -R tftp /var/lib/tftpboot
        service tftpd-hpa restart
        service tftpd-hpa status
        echo "Just a test file" >> /var/lib/tftpboot/test.file
    fi
}

function UninstallaptMysql {
    echo "Uninstalling Mysql"
    apt-get -y purge mysql-server mysql-client mysql-common \
    mysql-server-core-5.5 mysql-client-core-5.5
    rm -rf /etc/mysql /var/lib/mysql
    apt-get -y autoremove
    apt-get autoclean
}

function UninstallaptApache {
    service apache2 stop
    apt-get -y purge apache2*
    rm -rf /etc/apache2
    apt-get -y autoremove
    apt-get autoclean
}

